Initial
codex-team/capella.php pull request #1
Opened 2017-11-09 18:04 UTC by gohabereg

2017-11-09 20:04 UTC, neSpecc requested changes

2017-11-09 20:04 UTC, neSpecc commented on src/Capella.php
> + * @example
нужен readme и подключение через composer

2017-11-10 08:26 UTC, neSpecc requested changes

2017-11-10 08:26 UTC, neSpecc commented on src/Capella.php
> +    protected function sendRequest($url, array $params, $method='POST') {
может private?

2017-11-10 08:26 UTC, neSpecc commented on src/Capella.php
> +                foreach ($params as $key => $value) {
http://php.net/manual/en/function.http-build-query.php

2017-11-10 08:26 UTC, neSpecc commented on src/Capella.php
> +    protected function loadConfig() {
private

2017-11-10 08:26 UTC, neSpecc commented on src/Capella.php
> + * @package Capella
надо задокументировать авторство codex team и ссылку на гитхаб

2017-12-08 19:39 UTC, n0str requested changes

2017-12-08 19:39 UTC, n0str commented on src/Capella.php
> +        if (file_exists($path)) {
If the file does not exist (for ex. due to misprint) system decides that it's a URL. But it's not an URL.

2018-01-18 17:33 UTC, talyguryn approved these changes

2018-01-18 23:25 UTC, n0str approved these changes

2018-01-19 07:18 UTC, neSpecc requested changes

2018-01-19 07:18 UTC, neSpecc commented on README.md
> +$image = Capella::upload('path-or-url-to-your-pipcture');
picture

2018-01-19 07:18 UTC, neSpecc commented on README.md
> +$image = Capella::image('abcdef-1234-abcd-1234');
Provide link to the `static image($id)` SDK method description where User can read about parameters return value

2018-01-19 07:18 UTC, neSpecc commented on README.md
> +$url = $image->url();
Provide link to the `static upload()` SDK method description where User can read about parameters return value

2018-01-19 07:18 UTC, neSpecc commented on README.md
> +
Add link to the SDK methods description

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +This class provides two basic methods to work with Capella API.
methods for working with

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> + Upload image file to capella.pics, or send image URL.
Upload an `Image file` or send an `Image URL` to the Capella

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +This class provides two basic methods to work with Capella API.
`[Capella API](https://github.com/codex-team/capella#readme)`

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +| `path`    | `string` | Image URL or path to upload to capella.pics |
Image URL of File path that should be uploaded to the Capella

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +Otherwise throws [`CapellaImage`](#capellacapellaexception).
the CapellaException

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +Get [`CapellaImage`](#capellacapellaimage) object with passed `$id`
by passed

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +| `id`      | `string` | Image id, received from capella.pics |
unnecessary comma

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +Return [`CapellaImage`](#capellacapellaimage) object.
the

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +Upload images to capella using cURL.
to the Capella

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +Return `stdClass` object if path is valid and capella.pics is accessible.
and Capella

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +| `url`     | Uploaded image url |
URL

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +Throws [`CapellaImage`](#capellacapellaexception) if `path` is not existing file or valid and accessible URL.
the CapellaImageException (or CapellaException )

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +Throws [`CapellaImage`](#capellacapellaexception) if `path` is not existing file or valid and accessible URL.
> path is not existing file or valid and accessible URL. 

if passed `path` either invalid file link or inaccessible URL

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +| `url`    | Base image url |
URL

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +| `id`      | `string` | Image id, received from capella.pics |
from Capella

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +Return url to image with applied filters.
URL

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +Return url to image with applied filters.
to the Image

2018-01-19 07:18 UTC, neSpecc commented on README.md
> +This repository provides PHP SDK for working with capella.pics API
with the Capella API

2018-01-19 07:18 UTC, neSpecc commented on docs/sdk.md
> +| `id`      | `string` | Image id, received from capella.pics |
from the Capella

2018-01-19 07:18 UTC, neSpecc commented on src/Capella.php
> + *
`@link <api-docs-link>`

2018-01-19 07:18 UTC, neSpecc commented on src/Capella.php
> +     * Upload image to capella.pics
to the Capella

2018-01-19 07:18 UTC, neSpecc commented on src/Capella.php
> +     * @param string $path - path to image. Can be path to local file or external url
path to the Image. Can also be the Link to the local file or external URL

2018-01-19 07:18 UTC, neSpecc commented on src/Capella.php
> +            $errormsg = 'Upload to capella.pics failed.';
to the Capella

2018-01-19 07:18 UTC, neSpecc commented on src/CapellaImage.php
> + * Class to work with image filters.
for working

2018-01-19 07:18 UTC, neSpecc commented on src/Uploader.php
> + * Provide image uploading to Capella service
Image uploading to the

2018-01-19 07:18 UTC, neSpecc commented on src/Uploader.php
> +     * Upload image to capella service
to the Capella

2018-01-19 07:18 UTC, neSpecc commented on src/Uploader.php
> +     * @return \stdClass – array if path is valid and capella.pics is accessible or false
Capella

2018-01-19 07:18 UTC, neSpecc commented on src/Uploader.php
> +     * @return \stdClass – array if path is valid and capella.pics is accessible or false
> or false

otherwise is false

2018-01-19 07:18 UTC, neSpecc commented on src/Uploader.php
> +        throw new CapellaException('Path is not existing file or valid and accessible URL.');
Provided path links to the nonexistent/invalid file or inaccessible URL

2018-01-19 07:18 UTC, neSpecc commented on src/Uploader.php
> +     * Send cURL request to capella service
to the Capella

2018-01-19 18:40 UTC, gohabereg commented on docs/sdk.md
> +Get [`CapellaImage`](#capellacapellaimage) object with passed `$id`
Method doesn't get `CapellaImage` _by_ `id`. It just creates new `CapellaImage` object and pass `id` to the constructor.

2018-01-19 19:37 UTC, neSpecc approved these changes

2018-01-19 19:37 UTC, merged